language: node_js
node_js:
  - '8'

cache: npm

before_script:
  - git clone https://github.com/overcat/developers.git
  - cd developers
  - npm install --no-shrinkwrap
  - node_modules/.bin/gulp git:clone
  - cp -R ../translations/zh-Hans/* repos/docs/

script:
  - node_modules/.bin/gulp

deploy:
  provider: pages
  skip-cleanup: true
  github-token:
    secure: U1tEGlJ2G4xfidsBvd0e+oZbqXizFv0qjobhohiN83oAcuUT0JvX24g/Qm2A2mJPJQ5fye9P1fycJ39WH+jIQTk/Fd3yVQ5F2TWLOlepkXfmBkuvUaoUMbDhwbkRCf0wjjICx/Zqtbd7jZXYIfk4K5kgPJGDBLzhpjsAjsR32US1GMXH3VOVWiRdPSVBLSWp7bG26UaTYUf1xJ1Luemu9e0YIoWyboJF9Cs7BKXqHy8LIVP/JiE9ZOyjmMoXaJDUB4VK6FHazYq3tOTPzUASqUBTo/F6HVhjIYGq8D1yF1nQfL7OhUmOfLG0b7PnvznK/1rNCr2wV4Fzp7A4WU32XkWJN1YX64/wKyPlN39TPRo029gZYPFK8anJRC2FHNhOwlJkDI8zAkEWk9/IVl3cG90XHt0CU2JP3+FAKJemX3Zs6ZPyknV8KObYVvQjUfkik5l/XJF6hxG9sY4FCr9TC7fG1Iz1C77W7GXvtQwVrvSHW553PNcdsKT5fq2hY+XSK8cFXf5LSePydgIYQXdDm+Uqvd02iqvOryKNgvzPFLKJ3wDtf5IpgQ3KQ28LJg9adtonm1E1XI6uMVIIJu/lN4P2gE8rUUyWKuSAFIbkqn7yqhtH2tqKGNf6csqeCm1+st/MybSa7MGAKs+NJvUt3BrH6Za3KySd55I1fgcb46U=
  local-dir: developers/build
  fqdn: stellar-docs.overcat.me 
  on:
    branch: master

notifications:
  email: false
