language: node_js
node_js:
  - '8'

cache: npm

before_script:
  - git clone https://github.com/overcat/developers.git
  - cd developers
  - npm install --no-shrinkwrap
  - node_modules/.bin/gulp git:clone
  - cp -R ../translations/zh-Hans/* repos/docs/

script:
  - node_modules/.bin/gulp

deploy:
  provider: pages
  skip-cleanup: true
  github-token:
    secure: vA5STGYrH91Qz9+HpSDWvkK6eC29TEjaQ+fvNppMLSMfPJBsgSwCnbq7z8sxBJd4jdrWiswsyE07zch3sBbg4BUgGwVVA3TRFgVyRzTINLa5Bjp1KGCviiYBXTdFQ4Wmjyz2Mn+uLKdRAdcimHmoyXvNHsq/S0pUCnnbedOGeCXX5J6fHIM6ucyhgY7WNFeFvQgQV8T5CJm/viHMTwv7UJjitZjmnL1i2w+J5AJYx1bJ+vuLG/nrSbnRzNCUp50OK22xmkzL7CZL2qwVOpJHnFKQoR1jzQiHrbVs8FTNLI5tXMOck3oqsnRMCnrh1pwKhj72mBCMAfLSmB5oGXz+adPzqadw1YRdce8fEWubQXhgDYC1nfJz9BNvFqixkFfZYwdsJKkgzXNMVhOo9mK/HON9kbefPq+yXIBWJ9MgvRWmtRQe0GCX3oyFtgatl5AUWZjA9QCCHG6raUlNWx0GHTLRBiEIQA+il2Edc0punPQrya+UnrXk1DdhsPsDl8nD0k1dKPLUMOCdPhLjZzrHg0106i+CCQnELHsCFu4xwJmjwmQ7pCVNeJOfm6/5yXqVLd9UR+SuW7upLXa7y1Ag/fm1zkYDalumont7cqRK7sX8h2Zhj+2awE4jsIXBuaxa4PKCzsunx7/8dk8qke2FAwX/wh/8YTdLn+hyt4VCkI4=
  local-dir: developers/build
  fqdn: docs.stellarcn.org
  on:
    branch: master

notifications:
  email: false
